language: node_js
node_js:
  - "12"
  - "13"
env:
  - NODE_ENV=test RABBITMQ_URI=amqp://guest:guest@localhost:5672/haniot
addons:
  sauce_connect: true
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
  - mongodb
sudo: required
before_script:
  - docker pull influxdb
  - docker run -d -p 8086:8086 influxdb
  - sudo rabbitmqctl add_vhost haniot
  - sudo rabbitmqctl set_permissions -p haniot guest ".*" ".*" ".*"
  - npm install && npm install coveralls mocha-lcov-reporter --save-dev
script:
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls
notifications:
  email:
    on_success: never
    on_failure: always
