version: "3.8"
services:
  influxdb:
    image: influxdb
    container_name: haniot-influxdb
    ports:
      - 8086:8086
    restart: always
    volumes:
      - haniot-influxdb-data:/var/lib/influxdb
    networks:
      - haniot-network
    logging:
      driver: json-file
      options:
        max-size: 100m

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: haniot-rabbitmq
    restart: always
    ports:
      - 15672:15672 # Management UI
      - 5672:5672 # AMQP Protocol
    networks:
      - haniot-network
    logging:
      driver: json-file
      options:
        max-size: 100m

volumes:
  haniot-influxdb-data:
    name: haniot-influxdb

networks:
  haniot-network:
    name: haniot-network
    driver: bridge
